### ISSUE TITLE
TeamStats "win" boolean is always false.

### ISSUE THREAD

**Issue by OwenVey** [taycaldwell/riot-api-java#110]
I have ran a few tests grabbing team stats from a match and the isWin() method in TeamStats always returns false. I believe this is because the endpoint returns a string and isn't converted into a boolean in your wrapper correctly. However, the win field in ParticipantStats is a bool which works perfectly in your wrapper. If you need me to explain more let me know.

**Comment by taycaldwell** [comment]
Hey Owen. Thanks for bringing this to our attention. 

If you have a solution for this issue or have already fixed it yourself, keep in mind we accept PRs and contributions.

Otherwise, we will look into it and resolve this issue, ASAP.

Thank you.

**Comment by taycaldwell** [comment]
Apparently this field returns a display string (most likely used by the client or match history), and the legal values seem to be "Win" and "Fail".

We can potentially convert these display strings to their appropriate booleans on our side, or update the DTO to reflect the expected data type.

The only downside to converting it on our end rather than following the documentation is that Riot could potentially change the legal values at any time, or even worse give the data type more than two legal values, or values that can't clearly resolve to a boolean value (i.e. "Draw", "Tie", etc.)

**Comment by Linnun** [comment]
I have changed its datatype to String. We should stick to the documentation here IMO

**Comment by taycaldwell** [comment]
Thanks for the quick fix Linnun.

@OwenVey We have decided to fix the conversion issue, and stick to the official documentation of the API. Should you need the game conclusion data in boolean form, I would recommend making the conversion yourself, or utilizing the ParticipantStats DTO which has booleans for the game conclusion of each participant in the game.
