### ISSUE TITLE
Champion Data Issue

### ISSUE THREAD

**Issue by BennicTV** [taycaldwell/riot-api-java#122]
Hello,
first of all i am new to programming and just started a couple days ago for using this api so please dont condemn me for stupid questions (also for my english).

so basically i have two problems. I took one example from here and changed everything to get the champion Informations this includes in my case:
Name; Stats; Passive; Lore; Title; Skin; with the getMethods of it. 

The first thing is that my programm return for Stats; Passive; Lore; Skins;  
just "null" and not a the desired informations. 
The Second thing is that i have to commit the Champion Id in the method but the Champion IDs are pretty random and i wanna implement that you can just type the Name of a Champion to get the information about it. Is there a way to get the Champion information by name and not by the ID ?

This is my Code:
>import java.util.Scanner;
>
>import net.rithms.riot.api.ApiConfig;
>import net.rithms.riot.api.RiotApi;
>import net.rithms.riot.api.RiotApiException;
>import net.rithms.riot.api.endpoints.static_data.dto.Champion;
>import net.rithms.riot.constant.Platform;
>
>public class GetDataChampionExample {
>
>	private static Scanner scanner;
>
>	public static void main(String[] args) throws RiotApiException {
>		ApiConfig config = new ApiConfig().setKey("Key");
>		RiotApi api = new RiotApi(config);
>
>		scanner = new Scanner(System.in);
>		System.out.print("ID:");
>		int ID = scanner.nextInt();
>
>		Champion champion = api.getDataChampion(Platform.EUW, ID);
>		System.out.println("ID: " + ID);
>		System.out.println("Name: " + champion.getName());
>		System.out.println("Stats: " + champion.getStats());
>		System.out.println("Passive: " + champion.getPassive());
>		System.out.println("Lore: " + champion.getLore());
>		System.out.println("Title: " + champion.getTitle());
>		System.out.println("Skins: " + champion.getSkins());
>
>	}
>}

This is the return:
>ID:1
>ID: 1
>Name: Annie
>Stats: null
>Passive: null
>Lore: null
>Title: the Dark Child
>Skins: null

**Comment by taycaldwell** [comment]
Hi @BennicTV,

So the [getChampionById](https://developer.riotgames.com/api-methods/#lol-static-data-v3/GET_getChampionById) Riot Games API endpoint that backs the method you are calling doesn't return all data by default. The default response will only contain the champions name, title, id, and key.

You are currently using the method that asks for the default response:

```java
getDataChampion(Platform platform, int id);
```

To ask for more information than this, you will have to use the overloaded method, and provide additional 'tags' for the kind of data you wish to receive.

```java
 getDataChampion(Platform platform, int id, Locale locale, String version, ChampionTags... tags);
```

So your updated code might look something like this:

```java
Champion champion = api.getDataChampion(Platform.EUW, ID, null, null,
                ChampionTags.STATS, ChampionTags.PASSIVE, ChampionTags.LORE, ChampionTags.SKINS);
```

Alternatively, if you don't care too much about controlling the payload size of the response from the API, you can just provide `ChampionTags.ALL` as a tag to get all the possible champion data.

```java
Champion champion = api.getDataChampion(Platform.EUW, ID, null, null, ChampionTags.ALL);
```

To answer your second question, it is totally possible to create a program that looks up champion information by champion name.

You will still be querying for champion data using the champion's ID (as that is the unique identifier for the champion that the endpoint for the Riot Games API expects you to provide), however the trick it to make a request for all champion data and cache this data before the user asks you for a specific champion's data.

The Riot Games API provides a great endpoint to retrieve data for all champions in the game. The method for this endpoint is called `getDataChampionList`:

```java
ChampionList championList = api.getDataChampionList(Platform.EUW, null, null, false, ChampionListTags.ALL);
```

Unfortunately, the data is organized as a mapping from champion `key` to champion data objects, and keys aren't always the champion's name (i.e. Wukong's key is MonkeyKing). So, if you want to cache this data in a way that makes it easy to retrieve champion data by their name in a scalable way, you will have to get a bit fancy and use your own data structure as a cache rather than just using the map directly from the response.

Here's a simple example:

```java
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import net.rithms.riot.api.ApiConfig;
import net.rithms.riot.api.RiotApi;
import net.rithms.riot.api.RiotApiException;
import net.rithms.riot.api.endpoints.static_data.constant.ChampionListTags;
import net.rithms.riot.api.endpoints.static_data.dto.Champion;
import net.rithms.riot.api.endpoints.static_data.dto.ChampionList;
import net.rithms.riot.constant.Platform;

public class GetDataChampionExample {

    private static Scanner scanner;

    public static void main(String[] args) throws RiotApiException {
        ApiConfig config = new ApiConfig().setKey("key");
        RiotApi api = new RiotApi(config);

        ChampionList championList = api.getDataChampionList(Platform.EUW, null, null, false, ChampionListTags.ALL);
        Map<String, Champion> championByName = new HashMap<>();
        for (Champion champion : championList.getData().values()) {
            championByName.put(champion.getName().toLowerCase(), champion);
        }

        scanner = new Scanner(System.in);
        System.out.print("What champion would you like data for?");
        String name = scanner.next().toLowerCase();
        Champion champion = championByName.get(name);
        if (champion != null) {
            System.out.println("ID: " + champion.getId());
            System.out.println("Name: " + champion.getName());
            System.out.println("Stats: " + champion.getStats());
            System.out.println("Passive: " + champion.getPassive());
            System.out.println("Lore: " + champion.getLore());
            System.out.println("Title: " + champion.getTitle());
            System.out.println("Skins: " + champion.getSkins());
        } else {
            System.out.println("Sorry I don't recognize that champion name.");
        }
    }
}
```

Note, you will have to fix your print statements as most of the toString() methods will just print out the raw data representation of the object, not a pretty formatted string if that is what you are looking for.

Hope this helps. Let me know if you have anymore questions about using the API.

**Comment by BennicTV** [comment]
hi @taycaldwell,
thank you verry much this helped me a lot, but as output for stats i just have 
> Stats: net.rithms.riot.api.endpoints.static_data.dto.Stats@78123e82
and i am not sure what is the problem, because for me it look like its missing an import 
>net.rithms.riot.api.endpoints.static_data.dto.Stats
but dont know what the:
>@78123e82
means at the end also tried to import it but it didint work also i am not sure what the output should be, because of that i am a bit confused

**Comment by taycaldwell** [comment]
Hi @BennicTV,

The Stats class doesn't override the `toString()` method, so if you ever try printing a Stats object, it will print the object reference (Stats@78123e82), which is useless to you.

You will have to grab the stat fields you wish you display and print them individually using the corresponding getter methods for those fields.

**Comment by zhec2** [comment]
is this wrong?
Exception in thread "main" net.rithms.riot.api.RiotApiException: 403: Forbidden
	at net.rithms.riot.api.request.Request.execute(Request.java:181)
	at net.rithms.riot.api.request.Request.<init>(Request.java:94)
	at net.rithms.riot.api.EndpointManager.callMethodAndReturnDto(EndpointManager.java:52)
	at net.rithms.riot.api.RiotApi.getDataChampionList(RiotApi.java:642)

**Comment by Sandwich5** [comment]
I have the same problem as @zhec2 Is there any fix or workaround?

P.S In my case, this happens when `RiotApi.getDataChampionList` is called. I am using a development API key, I've checked not to be expired and also not to exceed the rate limits.
