### ISSUE TITLE
Depreciation of GetRecentMatchListByAccountId

### ISSUE THREAD

**Issue by beeNotice** [taycaldwell/riot-api-java#123]
Hi,

Why did you set the GetRecentMatchListByAccountId as Deprecated ? 
This endpoint still seams valid in Riot's documentation.

Thanks for your work and your help !

**Comment by Linnun** [comment]
That endpoint is no longer supported by Riot since #getMatchListByAccountId() can yield exactly the same result now. Instead they suggest using #getMatchListByAccountId(). It is not marked as deprecated in the official Api documentation yet, but since Riot explicitly recommends to not use it anymore, we decided to deprecate this method.

If you need exactly the behavior of that method, the following call should return the same result:

> getMatchListByAccountId(platform, accountId, null, null, null, -1, -1, -1, 20)


See: https://discussion.developer.riotgames.com/articles/3241/update-on-matchlist-and-recent-endpoints.html

**Comment by beeNotice** [comment]
Sorry, I didn't see this announcement, thanks a lot for your answer !
