### ISSUE TITLE
Asking about the api

### ISSUE THREAD

**Issue by VinciGP** [taycaldwell/riot-api-java#145]
Hello, I’m a student and i was thinking about doing an app like opgg programmed in java with ur api as a final project.
I contact you because i was wondering if you are going to continue updating the api, and to ask you if you know if there are gonna be any problem if the api is updated in a future cause the new season and I’m in process of programming that app. Will I have to change a lot of code to adapt the code to the changes of the api? What do you think?

Although most provably you don't have information about the changes riot will do in the api, you know the api and maybe you know how some changes would affect to the development of an app like this. I'm a "novice", I only 2 years learning programming and i was looking for advice. 

Thanks for your time, for your attention and for your great work with the api by the way.

**Comment by Renkon** [comment]
There have been some deprecations coming on lately.

As far as I know, there has been some progress but there's a release yet to be done.

Most v3 APIs have already been deprecated, is there any estimated release date for the v4 endpoints?

(I'm commenting on this issue since it's related to the request)

**Comment by Linnun** [comment]
@VinciGP 
We try to keep this API up-to-date, although right now we're a bit behind release schedule. As for breaking changes, when the Riot Api does a major versioning step (like most recently from v3 to v4) there are some breaking changes to be expected (just because the Riot Api works a bit different now). Changes like that are usually communicated by Riot approx. 90 days before enforcing it to give users time to migrate their project to the latest version.

@Renkon 
I'm currently in a testing stage with the current master branch -- and so far it seems stable. If you need it to work right now, I'd highly suggest to use the current master branch. But if no major issue comes up, I'll try to get a new release out this week. Sorry for being late on that.

**Comment by Linnun** [comment]
Bumping to let you know I've pushed a new release here: https://github.com/taycaldwell/riot-api-java/releases/tag/4.2.0
